# Generated by Django 5.2.5 on 2025-11-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('toname', models.CharField(max_length=200)),
                ('phno', models.CharField(max_length=20)),
                ('aadharno', models.CharField(max_length=20)),
                ('ap1', models.CharField(max_length=100)),
                ('ap2', models.CharField(blank=True, max_length=100)),
                ('aptdas', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
