# Generated by Django 5.2.5 on 2025-11-10 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('date', models.DateField(blank=True, default=datetime.date.today)),
                ('toname', models.CharField(max_length=200)),
                ('phno', models.CharField(max_length=10)),
                ('aadharno', models.CharField(max_length=12)),
                ('ap1', models.CharField(max_length=100)),
                ('ap2', models.CharField(blank=True, max_length=100)),
                ('aptdas', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('ap_district', models.CharField(blank=True, max_length=100)),
                ('ap_constitution', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
