# Generated by Django 5.2.5 on 2025-11-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pptapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentationdata',
            name='address',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
    ]
