# Generated by Django 5.2.5 on 2025-11-08 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pptapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationdata',
            name='entry_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='presentationdata',
            name='aadharno',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='presentationdata',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='presentationdata',
            name='phno',
            field=models.CharField(max_length=10),
        ),
    ]
