# Generated by Django 5.2.5 on 2025-11-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pptapp', '0002_alter_presentationdata_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationdata',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
