# Generated by Django 5.2.5 on 2025-11-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pptapp', '0003_presentationdata_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentationdata',
            name='date',
            field=models.DateField(blank=True, default='10/11/2025'),
        ),
    ]
