# Generated by Django 5.2.5 on 2025-11-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pptapp', '0004_alter_presentationdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentationdata',
            name='date',
            field=models.DateField(blank=True, default='13/11/2025'),
        ),
    ]
