# Generated by Django 5.2.5 on 2025-11-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pptapp', '0005_alter_presentationdata_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationdata',
            name='committee',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='presentationdata',
            name='date',
            field=models.DateField(blank=True, default='14/11/2025'),
        ),
    ]
